export * from './types'
export * from './render-target'
export { targets, allTargets } from './targets'
export { renderSlide, renderProject } from './compose'
export type { RenderedSlide } from './compose'
export * from './director'
export { renderTemplateSlide } from './template'
export type { TemplateOptions } from './template'
export { detectGeometry } from './detect'
export type { Geometry } from './detect'
